[pytest]
addopts =
    --base-url=https://opensource-demo.orangehrmlive.com/web/index.php
    --headed
    --browser chromium
    --slowmo 200
    --html=reports/report.html
    --self-contained-html

testpaths = tests